language: python

cache:
  directories:
  - lua_install
  - testrun/testing_cache-5.1
  - testrun/testing_cache-5.2
  - testrun/testing_cache-5.3
  - testrun/testing_cache-2.1
  - testrun/testing_server-5.1
  - testrun/testing_server-5.2
  - testrun/testing_server-5.3
  - testrun/testing_server-2.1
  
unit_script: &unit_script
  - busted -o gtest --exclude-tags=git,integration --verbose -Xhelper "lua_dir=$PWD/lua_install,travis"
  - busted -o gtest --exclude-tags=git,integration --verbose -Xhelper "lua_dir=$PWD/lua_install,travis,env=full"
  
integration_script: &integration_script
  - lua -v
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then shellcheck ./configure; fi
  - ./configure --with-lua=lua_install
  - ./makedist dev
  - busted -o gtest --exclude-tags=git,unit --verbose -Xhelper "lua_dir=$PWD/lua_install,travis"
  - busted -o gtest --exclude-tags=git,unit --verbose -Xhelper "lua_dir=$PWD/lua_install,travis,env=full"

deploy_script: &deploy_script
  - sudo apt-get install mingw-w64
  - ./configure --with-lua=lua_install
  - make
  - make windows-binary
  - make windows-pack

jobs:
  include:
    # Unit tests for linux
    - stage: unit
      script: *unit_script
      os: linux
      env:
        - LUA="lua=5.1"
    - stage: unit
      script: *unit_script
      os: linux
      env:
        - LUA="lua=5.2"
    - stage: unit
      script: *unit_script
      os: linux
      env:
        - LUA="lua=5.3"
    - stage: unit
      script: *unit_script
      os: linux
      env:
        - LUA="luajit=2.1"
    # Unit tests for osx
    - stage: unit
      script: *unit_script
      os: osx
      env:
        - LUA="lua=5.1"
      language: generic
    - stage: unit
      script: *unit_script
      os: osx
      env:
        - LUA="lua=5.2"
      language: generic
    - stage: unit
      script: *unit_script
      os: osx
      env:
        - LUA="lua=5.3"
      language: generic
    - stage: unit
      script: *unit_script
      os: osx
      env:
        - LUA="luajit=2.1"
      language: generic
    # Integration tests for linux
    - stage: integration
      script: *integration_script
      os: linux
      env:
        - LUA="lua=5.1"
    - stage: integration
      script: *integration_script
      os: linux
      env:
        - LUA="lua=5.2"
    - stage: integration
      script: *integration_script
      os: linux
      env:
        - LUA="lua=5.3"
    - stage: integration
      script: *integration_script
      os: linux
      env:
        - LUA="luajit=2.1"
    # Integration tests for osx
    - stage: integration
      script: *integration_script
      os: osx
      env:
        - LUA="lua=5.1"
      language: generic
    - stage: integration
      script: *integration_script
      os: osx
      env:
        - LUA="lua=5.2"
      language: generic
    - stage: integration
      script: *integration_script
      os: osx
      env:
        - LUA="lua=5.3"
      language: generic
    - stage: integration
      script: *integration_script
      os: osx
      env:
        - LUA="luajit=2.1"
      language: generic
    # Deploy Windows binary
    - stage: deploy
      script: *deploy_script
      os: linux
      addons:
        apt:
          packages:
          - mingw-w64
      env:
        - LUA="lua=5.3"
        - LUAROCKS_DEPLOY="yes"

before_install:
  - if [ ! -f lua_install/bin/luarocks ]; then pip2 install hererocks; fi
  - if [ ! -f lua_install/bin/luarocks ]; then hererocks lua_install -r^ --$LUA; fi
  - export PATH=$PATH:$PWD/lua_install/bin # Add directory with all installed binaries to PATH

install:
  - if [ ! -f lua_install/bin/busted ]; then luarocks install busted; fi
  - if [ ! -f lua_install/bin/luacov ]; then luarocks install cluacov; fi

after_success:
  - luacov -c $TRAVIS_BUILD_DIR/testrun/luacov.config
  - cd $TRAVIS_BUILD_DIR/testrun/ && bash <(curl -s https://codecov.io/bash)
  - grep "Summary" -B1 -A1000 $TRAVIS_BUILD_DIR/testrun/luacov.report.out

notifications:
  email:
    on_success: change
    on_failure: change
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/3320fc3f28abbb06e1d8
    on_success: change
    on_failure: always
    on_start: never

#deploy:
#  on:
#    branch: bintray
#    condition: "$LUAROCKS_DEPLOY" = "yes"
#  provider: bintray
#  file: "binary/bintray_descriptor.json"
#  user:
#    secure: FttIvDhFaLDp1EwJt5JS4ol4EuPr6yjW2HfOyXLMy9BxNWBDJ28w/Z8X0dRbNRKKNOmXMVuo2f/LozVhXq/yv6hQT453g18nKU9Ff7Yney1t9dq5u7H7NlfJ8Nf1rGJ8OMS/asxTzX/GlABPR7tpTWB3OektSNJP1yWjTw6AOHM=
#  key:
#    secure: Yq1/STo0q+5w0ZeKYfms4vyBlsvMgHWUGFVJDTZkIEnjE8ASijiS9yUKSBeHs6T7ynSQPc2cmzgPNk8jXkH5XG+tLPpw59SMqzanTA0FuBg1RLnPnTugbNuf7ficiTN1i++IveYlz+68qPBuClgc9+LxWEHp11xgiL/Pd0cv+oY=
#  skip_cleanup: true

